### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [CamCorliss/prj-rev-bwfs-dasmoto#2]
Alternatively, you could specify shared properties such as `font-family: helvetica;` for your `body` element. That way, all its children elements will automatically inherit these properties without you needing to specify it for each one:

```css
body {
  font-family: helvetica;
  ...
}
```

https://github.com/CamCorliss/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/Resources/CSS/style.css
